model:
  class_num: 1
  det_score_threshold: 0.05
  fastMode: true
  labels:
  - obj
  max_output_boxes: 50
  nms_iou_threshold: 0.3
  workspace:
  - 30
preprocess:
  height: 1024
  means:
  - 0
  - 0
  - 0
  stds:
  - 1
  - 1
  - 1
  width: 1024
